In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import sklearn
import sklearn.datasets
import sklearn.linear_model
import seaborn as sns


In [2]:
df=pd.read_csv("Datasets/Task1_data/Image1.txt")

In [3]:
df

-3.0002   -3.0379  1
0    -2.56010 -4.003400  1
1    -3.03620 -3.491100  1
2    -3.68670 -1.745400  1
3    -2.88520 -3.376100  1
4    -0.83721 -0.594330  1
5    -2.83250 -2.385200  1
6    -3.31000 -2.007300  1
7    -2.77490 -1.082500  1
8    -2.80700 -5.149300  1
9    -3.31630 -3.298100  1
10   -4.26750 -1.767100  1
11   -4.10410 -1.632900  1
12   -2.82460 -3.178200  1
13   -2.14130 -2.801900  1
14   -1.92650 -1.947600  1
15   -3.11060 -3.121400  1
16   -3.92910 -2.817900  1
17   -2.85170 -3.168600  1
18   -4.12200 -1.705400  1
19   -3.76010 -4.084000  1
20   -4.09570 -3.909800  1
21   -3.24320 -4.392000  1
22   -2.57580 -3.964700  1
23   -2.96550 -2.708900  1
24   -2.49830 -0.833080  1
25   -3.21560 -2.539800  1
26   -1.04680 -0.775550  1
27   -2.98750 -2.831000  1
28   -2.04190 -2.625200  1
29   -2.85760 -2.817900  1
...       ...       ... ..
9969  2.16760  2.221500  2
9970  3.36880  2.535100  2
9971  2.75060  3.258600  2
9972  2.88210  2.859300  2
9973  3.04750  2.123500  2
9974  5.11910  4.090200  2
9975  3.13210  2.305800  2
9976  2.77690  2.951900  2
9977  3.20410  2.663600  2
9978  4.74830  2.149900  2
9979  4.13460  4.121200  2
9980  4.70290 -0.000865  2
9981  4.37080  2.684100  2
9982  4.38060  3.655600  2
9983  2.94990  3.049600  2
9984  1.86950  2.153700  2
9985  1.98940  1.502700  2
9986  4.41050  1.210900  2
9987  1.31450  5.517400  2
9988  1.28800  2.168900  2
9989  3.35440  3.491800  2
9990  2.50470  1.828600  2
9991  3.41220  4.049200  2
9992  1.81740  4.032600  2
9993  2.40880  3.779700  2
9994  2.55860  4.722800  2
9995  1.69450  2.414200  2
9996  1.35490  2.959200  2
9997  1.85740  3.650300  2
9998  2.90620  2.305000  2

[9999 rows x 3 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 3 columns):
-3.0002    9999 non-null float64
-3.0379    9999 non-null float64
1          9999 non-null int64
dtypes: float64(2), int64(1)
memory usage: 234.4 KB


In [5]:
df.isnull().sum()

-3.0002    0
-3.0379    0
1          0
dtype: int64

In [6]:
order=np.random.permutation(len(df))

In [7]:
x=df.iloc[:,0:1].values
y=df.iloc[:,1:2].values
x1=df.iloc[:,:1].values

In [8]:
x1.shape

(9999, 1)

In [9]:
x

array([[-2.5601],
       [-3.0362],
       [-3.6867],
       ...,
       [ 1.3549],
       [ 1.8574],
       [ 2.9062]])

In [10]:
y

array([[-4.0034],
       [-3.4911],
       [-1.7454],
       ...,
       [ 2.9592],
       [ 3.6503],
       [ 2.305 ]])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=0)

In [13]:
X_train=np.hstack((np.ones_like(x_train),x_train))
X_test=np.hstack((np.ones_like(x_test),x_test))

In [14]:
X_train

array([[ 1.    ,  1.3835],
       [ 1.    , -1.9474],
       [ 1.    , -3.7237],
       ...,
       [ 1.    , -3.0316],
       [ 1.    ,  3.5761],
       [ 1.    , -2.6524]])

In [15]:
def Cost(X,y,theta=[[0],[0]]):
    m = y.size
    J = 0
    h = X.dot(theta)
    J =1/(2*m)*np.sum(np.square(h-y))
    return J

In [16]:
Cost(X_train,y_train)

4.979554680879263

In [17]:
def gradientDescent(X,y,theta=[[0],[0]],alpha=0.1,num_iters=1500):
    m = y.size
    J_history = np.zeros(num_iters)
    
    for i in np.arange(num_iters):
        h = X.dot(theta)
        theta = theta - alpha*(1/m)*(X.T.dot(h-y))
        J_history[i] = Cost(X,y,theta)
        return(theta,J_history)

In [18]:
theta , Cost_J = gradientDescent(X_train,y_train)
print('theta: ',theta.ravel())


theta:  [0.00192841 0.90102281]


In [19]:
Cost(X_train,y_train,theta)

0.9326902306732344

In [20]:
Cost(X_test,y_test,theta)

0.9541654334311932